- name: OpenShift Cluster Post Install Tasks
  hosts: localhost
  vars_files:
    - vault.yaml
  tasks:
    - name: Create Namespaces
      include_role:
        name: namespaces
      loop: "{{ namespaces }}"
      loop_control:
        loop_var: namespace
      tags:
        - namespaces
    
    - name: Create TLS Secrets
      include_role:
        name: tls-secret
      loop: "{{ tls_secrets[cluster_name] }}"
      loop_control:
        loop_var: tls_secret
      tags:
        - tls-secrets

    - name: Deploy "Sealed Secrets" for Kubernetes
      include_role:
        name: sealed-secrets
      tags:
        - sealed-secrets

    - name: Update CA Certs
      include_role:
        name: proxy
      tags:
        - proxy

    - name: Create Additional Worker MCPs
      include_role:
        name: worker-mcp
      loop: "{{ additional_worker_mcp }}"
      loop_control:
        loop_var: mcp
      tags:
        - mcp
        
    - name: Configure OAuth
      include_role:
        name: oauth-ldap
      tags:
        - oauth-ldap

    - name: Label Nodes
      include_role:
        name: label-nodes
      loop: "{{ nodes }}"
      loop_control:
        loop_var: node
      tags:
        - label-nodes

    - name: Install Operators
      include_role:
        name: install-operators
      loop: "{{ operators }}"
      loop_control:
        loop_var: oitem
      tags:
        - install-operators

    - name: Update Default Ingress Controller
      include_role:
        name: ingress-operator
      tags:
        - ingress-operator

    - name: Update API Server
      include_role:
        name: apiserver
      tags:
        - apiserver

    - name: Create Local Volumes
      include_role:
        name: localvolumes
      loop: "{{ localvolumes }}"
      loop_control:
        loop_var: volume
      tags:
        - localvolumes
    
    - name: Create Storage Cluster Service
      include_role:
        name: storagecluster
      tags:
        - storagecluster

    - name: Configure Registry
      include_role:
        name: registry
      tags:
        - registry

    - name: Configure Hub Cluster
      include_role:
        name: acm-add-hub
      tags:
        - acm-add-hub

    - name: Configure Spoke Clusters
      include_role:
        name: acm-add-spoke
      tags:
        - acm-add-spoke